-- ==============================================================================
-- 1. Create `dictionary_cache` table
--    Used to cache character definitions generated by the LLM
-- ==============================================================================
CREATE TABLE IF NOT EXISTS dictionary_cache (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  char VARCHAR(10) NOT NULL UNIQUE,
  pinyin VARCHAR(50) NOT NULL,
  radical VARCHAR(10),
  definition_en TEXT,
  definition_zh TEXT,
  words JSONB DEFAULT '[]'::jsonb,   -- Example: [{"word": "熊猫", "pinyin": "xióng māo", "meaning": "panda"}]
  sentences JSONB DEFAULT '[]'::jsonb, -- Example: [{"text": "这只猫很可爱。", "pinyin": "zhè zhī māo hěn kě ài.", "meaning": "This cat is very cute."}]
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS (Row Level Security) for `dictionary_cache`
ALTER TABLE dictionary_cache ENABLE ROW LEVEL SECURITY;

-- Everyone can read the cache
CREATE POLICY "dictionary_cache_select_policy" 
  ON dictionary_cache FOR SELECT 
  TO public 
  USING (true);

-- Only service role (backend) can insert or update cache
CREATE POLICY "dictionary_cache_service_policy" 
  ON dictionary_cache FOR ALL 
  TO service_role 
  USING (true);


-- ==============================================================================
-- 2. Create `flashcard_progress` table
--    Used to track spaced repetition progress for each user and character
-- ==============================================================================
CREATE TABLE IF NOT EXISTS flashcard_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  char VARCHAR(10) NOT NULL,
  
  -- Spaced Repetition Algorithm fields (SuperMemo-2 simplified)
  interval INTEGER DEFAULT 0,            -- Number of days until next review
  ease_factor REAL DEFAULT 2.5,          -- Ease factor (minimum 1.3)
  next_review_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Ensure a user only has one progress record per character
  UNIQUE (user_id, char)
);

-- Create an index for querying due flashcards efficiently
CREATE INDEX IF NOT EXISTS idx_flashcard_next_review ON flashcard_progress(user_id, next_review_date);

-- RLS (Row Level Security) for `flashcard_progress`
ALTER TABLE flashcard_progress ENABLE ROW LEVEL SECURITY;

-- Users can only read and update their own flashcards
CREATE POLICY "flashcard_progress_select_policy" 
  ON flashcard_progress FOR SELECT 
  TO authenticated 
  USING (auth.uid() = user_id);

CREATE POLICY "flashcard_progress_insert_policy" 
  ON flashcard_progress FOR INSERT 
  TO authenticated 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "flashcard_progress_update_policy" 
  ON flashcard_progress FOR UPDATE 
  TO authenticated 
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "flashcard_progress_delete_policy" 
  ON flashcard_progress FOR DELETE 
  TO authenticated 
  USING (auth.uid() = user_id);
