"""add jobs table

Revision ID: 7add98e5cd3e
Revises: d64a0057a026
Create Date: 2026-07-17 11:02:50.885533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7add98e5cd3e'
down_revision: Union[str, Sequence[str], None] = 'd64a0057a026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('instruction', sa.Text(), nullable=False, comment='任务指令'),
    sa.Column('type', sa.String(length=10), nullable=False, comment='任务类型: cron, every, at'),
    sa.Column('cron', sa.String(length=100), nullable=True, comment='Cron 表达式'),
    sa.Column('every_ms', sa.Integer(), nullable=True, comment='间隔毫秒'),
    sa.Column('at', sa.DateTime(), nullable=True, comment='指定触发时间点'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('last_run', sa.DateTime(), nullable=True, comment='上次运行时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('friends')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('company', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('wechat', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('jobs')
    # ### end Alembic commands ###
